default_context:
  chart_name: "shared"
  chart_namespace: "shared"
  chart_version: "0.1.2"
  need_dep_chart: "no"
  include_service: "no"
  include_inference_service: "yes"
  inference_service_storage_uri: "s3://inference-server-bucket/shared/default"
  include_sklearn_inference_service: "no"
  include_namespace: "yes"
  include_role: "yes"
  include_role_binding: "yes"
  include_service_account: "yes"
  include_virtual_service: "yes"
  virtual_service_cluster_domain: "ecmwf-inference-server"
  virtual_service_container_port: "80"
  virtual_service_gateway: "knative-serving/knative-ingress-gateway"
  include_sklearn_virtual_service: "no"
  include_external_s3_secret: "yes"  
  external_s3_secret_endpoint: "s3.waw3-2.cloudferro.com:443"
  external_s3_secret_region: "us-east-1"
  external_s3_secret_anon_credential: "false"
  external_s3_secret_https: "1"
  k8s_s3_secret_name: "s3creds"
  external_s3_secret_data:
    "data": [
      {
        secret_key: "AWS_ACCESS_KEY_ID",
        vault_secret_key: "s3_cloudferro_creds/inference_server",
        vault_secret_property: "s3_access_key"
      },
      {
        secret_key: "AWS_SECRET_ACCESS_KEY",
        vault_secret_key: "s3_cloudferro_creds/inference_server",
        vault_secret_property: "s3_secret_key"
      }
    ]
  include_external_registry_secret: "no"